package com.example.reviewer.report;

import com.example.reviewer.model.Category;
import com.example.reviewer.model.Finding;
import com.example.reviewer.model.Severity;

import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/** Renders the aggregated findings into a Markdown report for a PR comment. */
public final class MarkdownReporter {

    /** Marker so a CI step can find-and-update the same sticky comment. */
    public static final String MARKER = "<!-- ai-java-reviewer -->";

    public String render(List<Finding> findings, int filesReviewed) {
        StringBuilder sb = new StringBuilder();
        sb.append(MARKER).append('\n');
        sb.append("## \uD83E\uDD16 AI Java Review\n\n");

        if (findings.isEmpty()) {
            sb.append("No issues found across **")
              .append(filesReviewed)
              .append(filesReviewed == 1 ? "** changed Java file. \u2705\n" : "** changed Java files. \u2705\n");
            return sb.toString();
        }

        // Counts by severity, in severity order.
        Map<Severity, Long> bySeverity = findings.stream()
                .collect(Collectors.groupingBy(Finding::severity, Collectors.counting()));

        sb.append("Reviewed **").append(filesReviewed)
          .append(filesReviewed == 1 ? "** file" : "** files").append(" and found **")
          .append(findings.size()).append("** issue")
          .append(findings.size() == 1 ? "" : "s").append(".\n\n");

        sb.append("| Severity | Count |\n|---|---|\n");
        for (Severity sev : Severity.values()) {
            long count = bySeverity.getOrDefault(sev, 0L);
            if (count > 0) {
                sb.append("| ").append(sev.emoji()).append(' ').append(sev.name())
                  .append(" | ").append(count).append(" |\n");
            }
        }
        sb.append('\n');

        // Group findings by file, then list most-severe first within each file.
        Map<String, List<Finding>> byFile = findings.stream()
                .collect(Collectors.groupingBy(
                        f -> f.file() == null ? "(unknown)" : f.file(),
                        java.util.LinkedHashMap::new,
                        Collectors.toList()));

        for (Map.Entry<String, List<Finding>> entry : byFile.entrySet()) {
            sb.append("### `").append(entry.getKey()).append("`\n\n");
            entry.getValue().stream()
                    .sorted(Comparator.comparingInt(f -> f.severity().ordinal()))
                    .forEach(f -> appendFinding(sb, f));
        }

        sb.append("\n---\n");
        sb.append("<sub>Generated by AI Java Reviewer. ")
          .append("AI analysis can miss issues or flag false positives \u2014 use judgement.</sub>\n");
        return sb.toString();
    }

    private void appendFinding(StringBuilder sb, Finding f) {
        Severity sev = f.severity();
        Category cat = f.category();

        sb.append("<details>\n<summary>")
          .append(sev.emoji()).append(' ')
          .append("**").append(escape(f.title())).append("** \u2014 ")
          .append(sev.name()).append(" / ").append(cat.label())
          .append(" / ").append(f.confidence().name()).append(" confidence");
        if (f.line() != null && f.line() > 0) {
            sb.append(" (line ").append(f.line()).append(')');
        }
        sb.append("</summary>\n\n");

        sb.append(escape(f.description())).append("\n\n");

        if (f.cwe() != null && !f.cwe().isBlank()) {
            sb.append("**Reference:** ").append(escape(f.cwe())).append("\n\n");
        }
        if (f.suggestion() != null && !f.suggestion().isBlank()) {
            sb.append("**Suggested fix:** ").append(escape(f.suggestion())).append('\n');
        }
        sb.append("\n</details>\n\n");
    }

    /** Minimal escaping so titles/descriptions don't break the surrounding Markdown. */
    private static String escape(String s) {
        if (s == null) return "";
        return s.replace("<", "&lt;").replace(">", "&gt;");
    }
}
